// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7fWR0weQeVOiA0Vzun9gjfbsGI9IuO9I',
    appId: '1:252134448697:web:22b1782fb8ebcbfef677e8',
    messagingSenderId: '252134448697',
    projectId: 'mental-health-app-4c926',
    authDomain: 'mental-health-app-4c926.firebaseapp.com',
    storageBucket: 'mental-health-app-4c926.firebasestorage.app',
    measurementId: 'G-TYMM4WTYLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNlfqzVpxKt-f-ZlX2ze0qyKfJQ8ThTiw',
    appId: '1:252134448697:android:ea0417bbcd9827d2f677e8',
    messagingSenderId: '252134448697',
    projectId: 'mental-health-app-4c926',
    storageBucket: 'mental-health-app-4c926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvdPI2LmlOw7iibDPVTJs5P65TQaryh8I',
    appId: '1:252134448697:ios:9ce22f2b3267059cf677e8',
    messagingSenderId: '252134448697',
    projectId: 'mental-health-app-4c926',
    storageBucket: 'mental-health-app-4c926.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvdPI2LmlOw7iibDPVTJs5P65TQaryh8I',
    appId: '1:252134448697:ios:9ce22f2b3267059cf677e8',
    messagingSenderId: '252134448697',
    projectId: 'mental-health-app-4c926',
    storageBucket: 'mental-health-app-4c926.firebasestorage.app',
    iosBundleId: 'com.example.start',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7fWR0weQeVOiA0Vzun9gjfbsGI9IuO9I',
    appId: '1:252134448697:web:ea8199a0346d4d7df677e8',
    messagingSenderId: '252134448697',
    projectId: 'mental-health-app-4c926',
    authDomain: 'mental-health-app-4c926.firebaseapp.com',
    storageBucket: 'mental-health-app-4c926.firebasestorage.app',
    measurementId: 'G-0XHYGSG8EK',
  );
}
